import pytest

from solution import Rucksack, get_mistakes, get_priority, main

example_input = [
    [
        "v",
        "J",
        "r",
        "w",
        "p",
        "W",
        "t",
        "w",
        "J",
        "g",
        "W",
        "r",
        "h",
        "c",
        "s",
        "F",
        "M",
        "M",
        "f",
        "F",
        "F",
        "h",
        "F",
        "p",
    ],
    [
        "j",
        "q",
        "H",
        "R",
        "N",
        "q",
        "R",
        "j",
        "q",
        "z",
        "j",
        "G",
        "D",
        "L",
        "G",
        "L",
        "r",
        "s",
        "F",
        "M",
        "f",
        "F",
        "Z",
        "S",
        "r",
        "L",
        "r",
        "F",
        "Z",
        "s",
        "S",
        "L",
    ],
    [
        "P",
        "m",
        "m",
        "d",
        "z",
        "q",
        "P",
        "r",
        "V",
        "v",
        "P",
        "w",
        "w",
        "T",
        "W",
        "B",
        "w",
        "g",
    ],
    [
        "w",
        "M",
        "q",
        "v",
        "L",
        "M",
        "Z",
        "H",
        "h",
        "H",
        "M",
        "v",
        "w",
        "L",
        "H",
        "j",
        "b",
        "v",
        "c",
        "j",
        "n",
        "n",
        "S",
        "B",
        "n",
        "v",
        "T",
        "Q",
        "F",
        "n",
    ],
    [
        "t",
        "t",
        "g",
        "J",
        "t",
        "R",
        "G",
        "J",
        "Q",
        "c",
        "t",
        "T",
        "Z",
        "t",
        "Z",
        "T",
    ],
    [
        "C",
        "r",
        "Z",
        "s",
        "J",
        "s",
        "P",
        "P",
        "Z",
        "s",
        "G",
        "z",
        "w",
        "w",
        "s",
        "L",
        "w",
        "L",
        "m",
        "p",
        "w",
        "M",
        "D",
        "w",
    ],
]


def test_example_input() -> None:
    assert main(example_input) == 157


@pytest.mark.parametrize(
    "rucksack, mistakes",
    [
        (example_input[0], {"p"}),
        (example_input[1], {"L"}),
        (example_input[2], {"P"}),
        (example_input[3], {"v"}),
        (example_input[4], {"t"}),
        (example_input[5], {"s"}),
    ],
)
def test_get_mistakes(rucksack: Rucksack, mistakes: set[str]) -> None:
    assert get_mistakes(rucksack) == mistakes


@pytest.mark.parametrize(
    "mistakes, priority",
    [
        ("p", 16),
        ("L", 38),
        ("P", 42),
        ("v", 22),
        ("t", 20),
        ("s", 19),
        ("a", 1),
        ("z", 26),
        ("A", 27),
        ("Z", 52),
    ],
)
def test_get_mistakes(mistakes: set[str], priority: int) -> None:
    assert get_priority(mistakes) == priority
